# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "passwordhasher.vvb"
      vb.gui = false
      vb.memory = "512"
    end
    #config.vm.provision :shell, :path => "bootstrap.sh"
    config.vm.synced_folder "../", "/home/vagrant/passwordhasher", owner: "vagrant", group: "vagrant"
    config.vm.network :forwarded_port, guest: 22, host: 2252, id: 'ssh', auto_correct: true
    config.vm.network "private_network", ip: "192.168.56.171"
end
