# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |v|
      v.name = "passwordhasher-dev"
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--memory", "384"]
    end
    config.vm.provision :shell, :path => "bootstrap.sh"
    config.vm.synced_folder "../", "/home/vagrant/passwordhasher", owner: "vagrant", group: "vagrant"
    config.vm.network :forwarded_port, guest: 22, host: 2252, id: 'ssh', auto_correct: true
    config.vm.network "private_network", ip: "192.168.56.132"
end
