#!/bin/bash
#
# This script invokes the PasswordHasher
# 
#
# author: andkrup@gmail.com
#
read -s -p "salt: " salt
echo ""
DIR="$( cd "$( dirname "$0" )" && pwd )"

java -jar "$DIR/PasswordHasher.jar" -salt "$salt"