#!/bin/bash
#
# This script invokes the PasswordHasher
# 
#
# author: andkrup@gmail.com
#
DOMAIN="$1"
# retrieve salt
read -s -p "salt: " salt
echo ""
DIR="$( cd "$( dirname "$0" )" && pwd )"

# retrieve domain name value from parameters
if [ ! -n "$DOMAIN" ]
then
	java -jar "$DIR/PasswordHasher.jar" -salt "$salt"
else
	java -jar "$DIR/PasswordHasher.jar" -salt "$salt" -domain "$DOMAIN"
fi

